CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE TYPE memory_type AS ENUM ('PROFILE','PREFERENCE','GOAL','FACT','KNOWLEDGE','PROJECT');
CREATE TYPE task_status AS ENUM ('TODO','DONE');
CREATE TYPE message_role AS ENUM ('USER','ASSISTANT','SYSTEM');
CREATE TABLE users (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text, email text NOT NULL UNIQUE, email_verified timestamptz, image text, password_hash text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE accounts (user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, type text NOT NULL, provider text NOT NULL, provider_account_id text NOT NULL, refresh_token text, access_token text, expires_at integer, token_type text, scope text, id_token text, session_state text, PRIMARY KEY (provider, provider_account_id));
CREATE TABLE sessions (session_token text PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires timestamptz NOT NULL);
CREATE TABLE verification_tokens (identifier text NOT NULL, token text NOT NULL, expires timestamptz NOT NULL, PRIMARY KEY (identifier, token));
CREATE TABLE profiles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE, display_name varchar(120) NOT NULL, primary_goal text, about text, onboarding_completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE goals (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, title varchar(180) NOT NULL, description text, archived boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE tasks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, goal_id uuid REFERENCES goals(id) ON DELETE SET NULL, title varchar(180) NOT NULL, notes text, status task_status NOT NULL DEFAULT 'TODO', due_date timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE memories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, type memory_type NOT NULL, content text NOT NULL, importance integer NOT NULL DEFAULT 3 CHECK (importance BETWEEN 1 AND 5), source varchar(120) NOT NULL DEFAULT 'USER', embedding_model text, embedding_metadata text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE conversations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE, title varchar(180) NOT NULL DEFAULT 'New conversation', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), conversation_id uuid NOT NULL REFERENCES conversations(id) ON DELETE CASCADE, role message_role NOT NULL, content text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX goals_user_id_idx ON goals(user_id);
CREATE INDEX tasks_user_id_idx ON tasks(user_id);
CREATE INDEX memories_user_id_idx ON memories(user_id);
CREATE INDEX conversations_user_id_idx ON conversations(user_id);
CREATE INDEX messages_conversation_id_idx ON messages(conversation_id);
