import { auth } from "@/auth";
import { archiveGoalAction, completeTaskAction, createGoalAction, createTaskAction, deleteTaskAction } from "@/server/actions";
import { listGoalsWithOpenTaskCounts, listTasks } from "@/server/repositories/core";

export default async function Tasks() {
  const session = await auth();
  const [goals, tasks] = await Promise.all([listGoalsWithOpenTaskCounts(session!.user.id), listTasks(session!.user.id)]);
  const activeGoals = goals.filter((goal) => !goal.archived);
  return <div className="grid gap-6"><div><p className="text-sm uppercase tracking-widest text-violet-300">Planning</p><h1 className="text-4xl font-bold">Tasks & Goals</h1></div><section className="grid gap-4 lg:grid-cols-2"><form action={createGoalAction} className="card grid gap-3"><h2 className="text-2xl font-bold">New goal</h2><input name="title" placeholder="Goal title" required maxLength={180}/><textarea name="description" placeholder="Description" maxLength={2000}/><button>Create goal</button></form><form action={createTaskAction} className="card grid gap-3"><h2 className="text-2xl font-bold">New task</h2><input name="title" placeholder="Task title" required maxLength={180}/><textarea name="notes" placeholder="Notes" maxLength={2000}/><select name="goalId"><option value="">No goal</option>{activeGoals.map(g => <option value={g.id} key={g.id}>{g.title}</option>)}</select><button>Create task</button><p className="text-sm text-slate-400">Goal ownership is verified on the server before a task is attached.</p></form></section><section className="card"><h2 className="text-2xl font-bold">Goals</h2><div className="mt-4 grid gap-3">{goals.length ? goals.map(g => <div key={g.id} className="rounded-xl bg-slate-900 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{g.title}{g.archived ? " (archived)" : ""}</p>{g.description ? <p className="text-sm text-slate-400">{g.description}</p> : null}<p className="mt-1 text-sm text-violet-300">{g.openTaskCount} open tasks</p></div>{!g.archived && <form action={archiveGoalAction.bind(null, g.id)}><button>Archive</button></form>}</div><div className="mt-3 grid gap-2">{tasks.filter(t => t.goalId === g.id).map(t => <div key={t.id} className="flex justify-between rounded-lg border border-slate-800 p-2 text-sm"><span>{t.status === "DONE" ? "✓ " : ""}{t.title}</span>{t.status !== "DONE" && <form action={completeTaskAction.bind(null, t.id)}><button>Complete</button></form>}</div>)}</div></div>) : <p className="text-slate-400">Create a goal to organize your tasks.</p>}</div></section><section className="card"><h2 className="text-2xl font-bold">All tasks</h2><div className="mt-4 grid gap-3">{tasks.length ? tasks.map(t => <div key={t.id} className="flex flex-wrap justify-between gap-3 rounded-xl bg-slate-900 p-3"><span>{t.status === "DONE" ? "✓ " : ""}{t.title}</span><div className="flex gap-2">{t.status !== "DONE" && <form action={completeTaskAction.bind(null, t.id)}><button>Complete</button></form>}<form action={deleteTaskAction.bind(null, t.id)}><button className="bg-rose-600">Delete</button></form></div></div>) : <p className="text-slate-400">No tasks yet.</p>}</div></section></div>;
}
