import { auth } from "@/auth";
import { deleteMemoryAction, upsertMemoryAction } from "@/server/actions";
import { listMemories } from "@/server/repositories/core";
import { memoryTypes } from "@/lib/validation/core";

export default async function Memory({ searchParams }: { searchParams?: Promise<{ q?: string; type?: string }> }) {
  const session = await auth();
  const params = await searchParams;
  const rows = await listMemories(session!.user.id, { query: params?.q, type: params?.type });
  const important = rows.filter((memory) => memory.importance >= 4).slice(0, 3);
  return <div className="grid gap-6"><div><p className="text-sm uppercase tracking-widest text-violet-300">Persistent context</p><h1 className="text-4xl font-bold">Memory</h1><p className="mt-2 text-slate-300">Review, search, edit, or delete memories. LumaOS only writes new memories when you save or accept a suggestion.</p></div><form className="card grid gap-3 md:grid-cols-4"><input name="q" defaultValue={params?.q ?? ""} placeholder="Search memories" className="md:col-span-2"/><select name="type" defaultValue={params?.type ?? ""}><option value="">All types</option>{memoryTypes.map(t => <option key={t}>{t}</option>)}</select><button>Filter</button></form><form action={upsertMemoryAction} className="card grid gap-3 md:grid-cols-4"><select name="type">{memoryTypes.map(t => <option key={t}>{t}</option>)}</select><input name="content" placeholder="What should LumaOS remember?" required className="md:col-span-2" maxLength={4000}/><input name="importance" type="number" min="1" max="5" defaultValue="3"/><button>Create memory</button></form>{important.length ? <section className="card"><h2 className="text-2xl font-bold">Important memories</h2><div className="mt-4 grid gap-3">{important.map(m => <div key={m.id} className="rounded-xl bg-slate-900 p-3"><p className="text-xs text-violet-300">{m.type} · source {m.source} · importance {m.importance}</p><p>{m.content}</p></div>)}</div></section> : null}<section className="grid gap-3"><h2 className="text-2xl font-bold">Recent memories</h2>{rows.length ? rows.map(m => <div className="card" key={m.id}><p className="mb-3 text-xs text-violet-300">{m.type} · source {m.source} · importance {m.importance}</p><form action={upsertMemoryAction} className="grid gap-3 md:grid-cols-5"><input type="hidden" name="id" value={m.id}/><select name="type" defaultValue={m.type}>{memoryTypes.map(t => <option key={t}>{t}</option>)}</select><input name="content" defaultValue={m.content} className="md:col-span-2" maxLength={4000}/><input name="importance" type="number" min="1" max="5" defaultValue={m.importance}/><button>Save</button></form><form action={deleteMemoryAction.bind(null, m.id)} className="mt-2"><button className="bg-rose-600">Delete</button></form></div>) : <div className="card border-dashed text-slate-400">No memories match this view.</div>}</section></div>;
}
